version: "3.8"

services:
  recipe:
    image: matheusmhmelo/api-recipe:latest
    ports:
      - 8082:8080
    volumes:
      - ./docker-config.yaml:/config.yaml
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
    networks:
      main:
        aliases:
          - recipe
  recipe_redis:
    image: redis
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 15s
    networks:
      main:
        aliases:
          - recipe_redis
networks:
  main:
    external: true