# Server configuration
server:
  port: ":8080"

# Recipe Puppy
recipe_puppy:
  url: "http://www.recipepuppy.com/api/?i=%s&p=%s"

# Giphy
giphy:
  url: "http://api.giphy.com/v1/gifs/search?api_key=%s&q=%s&limit=1&lang=en&rating=g"
  api_key: "pPiMNFkdnBt4wGmBiJ9YCryAw3lHJk98"